#!/usr/bin/env ruby
require 'terrun'

module Entity
  class Compiler < TerminalRunner
    name "entity"

    option "--help", 0, "", "Show this help document"
    help ""

    def self.run
      if @@options.include? "--help"
        show_usage
        exit
      end

      input = ANTLR3::FileStream.new('example.e')
      lexer = Entity::Lexer.new(input)
      tokens = ANTLR3::CommonTokenStrea.new(lexer)
    end
  end
end

if __FILE__ == $0
  x = Entity::Compiler.start(ARGV)
end